### ISSUE TITLE
Not compatible with Rails 4.2

### ISSUE THREAD

**Issue by salmanasiddiqui** [FineLinePrototyping/activerecord-custom_timestamps#1]
In rails 4.2, `create_record` and `update_record` methods have been changed to `_create_record` and `_update_record`.
reference: [9694f89] (https://github.com/prathamesh-sonpatki/rails/commit/9694f86de65e9162a6802a43cdbce9ccc85285b5)

Changing the method names directly into the gem is making it work fine. But ofcourse this will break the support for Rails 4.0-4.1..
Let me know the best way to fix this issue. I dont want to put the source code of this gem into vendor and then make changes in model.rb.

Im trying to add `alias_method :_create_record :create_record` in the module Model, but this is not working
`NoMethodError: super: no superclass method 'create_record' for #<Xyz:0x00000006588b48>`

**Comment by garysweaver** [comment]
Updated in master. Let me know if that works and if so, I'll release.

**Comment by salmanasiddiqui** [comment]
Works fine. :+1:

**Comment by garysweaver** [comment]
Fixed in v0.3.0.
