### ISSUE TITLE
uninitialized constant CustomTimestamps::EarlyRails4Model (NameError)

### ISSUE THREAD

**Issue by danielbucher** [FineLinePrototyping/activerecord-custom_timestamps#2]
Can't find CustomTimestamps::EarlyRails4Model module when using gem version 0.3.0 with rails 4.1.6. 
The error occurs when I try opening a rails console.

**Comment by garysweaver** [comment]
Should be fixed in 0.3.1. Thanks for the report!

**Comment by garysweaver** [comment]
Released in 0.3.1

**Comment by danielbucher** [comment]
@garysweaver great, thanks!
